// ============================================================================
//  SKYVAULT Royale - engine/render/GLFuncList.h
//  Lista unica de funciones GL usadas por el motor (subconjunto comun
//  OpenGL 4.6 core / GLES3, sin DSA). Se expande con el macro SVGL(ret, name, args).
//  NO incluir directamente; lo usan GLLoader.h / GLLoader.cpp.
// ============================================================================
SVGL(u32,         glCreateShader,          u32)
SVGL(void,        glShaderSource,          u32, i32, const char* const*, const i32*)
SVGL(void,        glCompileShader,         u32)
SVGL(void,        glGetShaderiv,           u32, u32, i32*)
SVGL(void,        glGetShaderInfoLog,      u32, i32, i32*, char*)
SVGL(void,        glDeleteShader,          u32)
SVGL(u32,         glCreateProgram,         )
SVGL(void,        glAttachShader,          u32, u32)
SVGL(void,        glLinkProgram,           u32)
SVGL(void,        glGetProgramiv,          u32, u32, i32*)
SVGL(void,        glGetProgramInfoLog,     u32, i32, i32*, char*)
SVGL(void,        glDeleteProgram,         u32)
SVGL(void,        glUseProgram,            u32)
SVGL(i32,         glGetUniformLocation,    u32, const char*)
SVGL(i32,         glGetAttribLocation,    u32, const char*)
SVGL(void,        glBindAttribLocation,    u32, u32, const char*)
SVGL(void,        glUniform1i,             i32, i32)
SVGL(void,        glUniform1f,             i32, f32)
SVGL(void,        glUniform2f,             i32, f32, f32)
SVGL(void,        glUniform3f,             i32, f32, f32, f32)
SVGL(void,        glUniform4f,             i32, f32, f32, f32, f32)
SVGL(void,        glUniform1fv,            i32, i32, const f32*)
SVGL(void,        glUniform3fv,            i32, i32, const f32*)
SVGL(void,        glUniform4fv,            i32, i32, const f32*)
SVGL(void,        glUniformMatrix3fv,      i32, i32, u8, const f32*)
SVGL(void,        glUniformMatrix4fv,      i32, i32, u8, const f32*)

SVGL(void,        glGenVertexArrays,       i32, u32*)
SVGL(void,        glDeleteVertexArrays,    i32, const u32*)
SVGL(void,        glBindVertexArray,       u32)
SVGL(void,        glGenBuffers,            i32, u32*)
SVGL(void,        glDeleteBuffers,         i32, const u32*)
SVGL(void,        glBindBuffer,            u32, u32)
SVGL(void,        glBufferData,            u32, isize, const void*, u32)
SVGL(void,        glBufferSubData,         u32, isize, isize, const void*)
SVGL(void,        glEnableVertexAttribArray, u32)
SVGL(void,        glDisableVertexAttribArray, u32)
SVGL(void,        glVertexAttribPointer,   u32, i32, u32, u8, i32, const void*)
SVGL(void,        glVertexAttribDivisor,   u32, u32)
SVGL(void,        glDrawArrays,            u32, i32, i32)
SVGL(void,        glDrawElements,          u32, i32, u32, const void*)
SVGL(void,        glDrawArraysInstanced,   u32, i32, i32, i32)
SVGL(void,        glDrawElementsInstanced, u32, i32, u32, const void*, i32)

SVGL(void,        glGenTextures,           i32, u32*)
SVGL(void,        glDeleteTextures,        i32, const u32*)
SVGL(void,        glBindTexture,           u32, u32)
SVGL(void,        glActiveTexture,         u32)
SVGL(void,        glTexImage2D,            u32, i32, i32, i32, i32, i32, u32, u32, const void*)
SVGL(void,        glTexSubImage2D,         u32, i32, i32, i32, i32, i32, u32, u32, const void*)
SVGL(void,        glTexParameteri,         u32, u32, i32)
SVGL(void,        glGenerateMipmap,        u32)
SVGL(void,        glPixelStorei,           u32, i32)

SVGL(void,        glGenFramebuffers,       i32, u32*)
SVGL(void,        glDeleteFramebuffers,    i32, const u32*)
SVGL(void,        glBindFramebuffer,       u32, u32)
SVGL(void,        glFramebufferTexture2D,  u32, u32, u32, u32, i32)
SVGL(u32,         glCheckFramebufferStatus, u32)

SVGL(void,        glEnable,                u32)
SVGL(void,        glDisable,               u32)
SVGL(void,        glViewport,              i32, i32, i32, i32)
SVGL(void,        glScissor,               i32, i32, i32, i32)
SVGL(void,        glClearColor,            f32, f32, f32, f32)
SVGL(void,        glClear,                 u32)
SVGL(void,        glDepthFunc,             u32)
SVGL(void,        glDepthMask,             u8)
SVGL(void,        glCullFace,              u32)
SVGL(void,        glFrontFace,             u32)
SVGL(void,        glBlendFunc,             u32, u32)
SVGL(void,        glBlendFuncSeparate,     u32, u32, u32, u32)
SVGL(void,        glBlendEquation,         u32)
SVGL(void,        glColorMask,             u8, u8, u8, u8)
SVGL(void,        glPolygonOffset,         f32, f32)
SVGL(void,        glLineWidth,             f32)
SVGL(u32,         glGetError,              )
SVGL(void,        glGetIntegerv,           u32, i32*)
SVGL(const u8*,   glGetString,             u32)
SVGL(void,        glReadPixels,            i32, i32, i32, i32, u32, u32, void*)
